### ISSUE TITLE
Нарисовать Use-case диаграмму сервиса рейтинга

### ISSUE THREAD

**Issue by ToToshka45** [ToToshka45/GameBy#21]

**Comment by KonstantinBenenson** [comment]
![Image](https://github.com/user-attachments/assets/a2fc4917-9cf4-4d5f-bc50-66ea26124d16)

**Comment by KonstantinBenenson** [comment]
https://app.diagrams.net/#

**Comment by KonstantinBenenson** [comment]
![Image](https://github.com/user-attachments/assets/a151b726-821a-4d53-b556-581fc12b4e72)

V1

**Comment by KonstantinBenenson** [comment]
![Image](https://github.com/user-attachments/assets/fe61009a-b2d7-49d7-b46d-f4994d83c089)

V2
