### ISSUE TITLE
Нарисовать ER диаграмму сервиса рейтинга

### ISSUE THREAD

**Issue by ToToshka45** [ToToshka45/GameBy#22]
https://lucid.app/lucidchart/93664716-16eb-43a6-8e75-1231591740e4/edit?view_items=z9Fg31J6kVlR&invitationId=inv_75e29981-3167-48bf-a37d-e5877e0daae8

**Comment by KonstantinBenenson** [comment]
https://github.com/ToToshka45/GameBy/wiki/%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81-%D0%A0%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%D0%BE%D0%B2
V1 приложена в Вики

**Comment by KonstantinBenenson** [comment]
https://github.com/ToToshka45/GameBy/wiki/%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81-%D0%A0%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%D0%BE%D0%B2
Новая версия Диаграммы приложена

**Comment by KonstantinBenenson** [comment]
[Ratings Service (GameBy).pdf](https://github.com/user-attachments/files/17328758/Ratings.Service.GameBy.pdf)
