### ISSUE TITLE
Нарисовать Class диаграмму сервиса рейтинга

### ISSUE THREAD

**Issue by ToToshka45** [ToToshka45/GameBy#23]
Рабочая ссылка (доступно для просмотра)
https://lucid.app/lucidchart/11a75eb9-05e1-4268-b2a4-c01747f06a87/edit?beaconFlowId=62BDDF25DADC0A72&invitationId=inv_53412b44-3b26-426e-ab8c-e2b32025c86a&page=HWEp-vi-RSFO#

**Comment by KonstantinBenenson** [comment]
Ссылка на описание в Документации
https://github.com/ToToshka45/GameBy/wiki/%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81-%D0%A0%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%D0%BE%D0%B2
